#!/bin/bash
if [ -z "$1" ]; then
    echo "Usage: $0 <config set>"
    exit 1
fi

dir="$(dirname "$0")"
config_dir="$dir/$1"

if [ ! -d "$config_dir" ]; then
    echo "Invalid config set: $1"
    exit 2
fi

for file in "$config_dir"/*; do
    base="$(basename "$file")"
    copy="$HOME/.$base"
    cp "$file" "$copy"
done
